import pywhatkit as kit

def send_whatsapp_message(phone_number: str, message: str):
    try:
        kit.sendwhatmsg_instantly(phone_number, message)
        print("Message sent successfully!")
    except Exception as e:
        print("An error occurred:", e)

# Example usage
send_whatsapp_message("+919358111995", "Hello, this message is generated by Python.")
