import pywhatkit as kit

phone_number = "+919358111995" #Replace with the receipient's number(including country code)

message = "Hello, this messgae is generated by python."

kit.sendwhatmsg_instantly(phone_number, message)